export interface LabelFieldDef {
  id: string;
  label: string;
  custom?: boolean;
  type?: string;
  testValue?: string;
}

export const LabelFieldMap: Record<string, { label: string; fields: LabelFieldDef[] }> = {
  PACKAGE_LABEL: {
    label: "Package Label",
    fields: [
      { id: "package_id", label: "Package ID" },
      { id: "package_barcode", label: "Package Barcode", custom: true, type: "barcode", testValue: "#23i743465" },
      { id: "package_id_qr", label: "Package ID QR", custom: true, type: "qr", testValue: "#23i743465" },
      { id: "product_name", label: "Product Name", testValue: "test product" },
      { id: "strain_name", label: "Strain Name", testValue: "test strain" },
      { id: "store_name", label: "Store Name", testValue: "test store" },
      { id: "net_weight", label: "Net Weight", testValue: "X kg" },
      { id: "origin_id", label: "Origin ID" },
      { id: "sku", label: "SKU", testValue: "#XXXXX" },
      { id: "batch_id", label: "Batch ID", testValue: "12345080" },
      { id: "supplier_name", label: "Supplier Name", testValue: "Mr. X supplier" },
      { id: "supplier_license", label: "Supplier License", testValue: "#xxxxxx" },
      { id: "test_results", label: "Test Results", testValue: "test result" },
      { id: "test_results_qr", label: "Test Results QR", custom: true, type: "qr", testValue: "test result" },
      { id: "total_terpenes", label: "Total Responses", testValue: "0" },
      { id: "product_category", label: "Product Category", testValue: "x category" },
      { id: "product_price", label: "Product Price", testValue: "$0.00" },
      { id: "expiration_date", label: "Expiration Date", testValue: "1st January, 1900" },
      { id: "package_text", label: "Package Text", testValue: "test package text" },
      { id: "current_datetime", label: "Date & Time", custom: true },
      { id: "metrc_tag", label: "Metrc Tag" },
    ],
  },
  EXIT_LABEL: {
    label: "Exit Label",
    fields: [
      { id: "product_name", label: "Product Name", testValue: "test product" },
      { id: "order_date", label: "Order Date", testValue: "1st January, 1900" },
      { id: "patient_name", label: "OrderName", testValue: "Mr. X" },
      { id: "patient_license", label: "Patient License", testValue: "#XXXXXX" },
      { id: "strain_name", label: "Strain Name", testValue: "test strain" },
      { id: "store_name", label: "Store Name", testValue: "test store" },
      { id: "store_license", label: "Store License", testValue: "#xxxxxxx" },
      { id: "net_weight", label: "Net Weight", testValue: "x kg" },
      { id: "mj_weight", label: "MJ Weight", testValue: "x kg/bag" },
      { id: "origin_id", label: "Origin ID", testValue: "#xxxxxx" },
      { id: "sku", label: "SKU", testValue: "#xxxxx" },
      { id: "package_id", label: "Package ID", testValue: "#xxxxx" },
      { id: "batch_id", label: "Batch ID", testValue: "#xxxxx" },
      { id: "harvest_date", label: "Harvest Date", testValue: "1st January, 1900" },
      { id: "manufacture_date", label: "Manufacture Date", testValue: "1st January, 1900" },
      { id: "date_tested", label: "Date Tested" },
      { id: "supplier_name", label: "Supplier Name", testValue: "Mr. X supplier" },
      { id: "supplier_license", label: "Supplier License", testValue: "#xxxxxx" },
      { id: "test_results", label: "Test Results", testValue: "x result" },
      { id: "test_results_qr", label: "Test Results QR", custom: true, type: "qr", testValue: "x result" },
      { id: "test_lab_name", label: "Test Lab Name" },
      { id: "test_facility_license", label: "Test Facility License" },
      { id: "test_results_url", label: "Test Results URL" },
      { id: "total_terpenes", label: "Total Responses", testValue: "0" },
      { id: "product_category", label: "Product Category", testValue: "x cateogry" },
      { id: "product_price", label: "Product Price", testValue: "$0.00" },
      { id: "expiration_date", label: "Expiration Date", testValue: "1st January, 1900" },
      { id: "current_datetime", label: "Date & Time", custom: true },
    ],
  },
  RECEIPT: {
    label: "Receipt",
    fields: [
      { id: "company_logo", label: "Company Logo", custom: true, type: "image", testValue: "/images/32.png" },
      { id: "print_date", label: "Print Date" },
      { id: "store_id", label: "Store ID", testValue: "#xxxxxx" },
      { id: "order_id", label: "Order ID", testValue: "#xxxxx" },
      { id: "store_name", label: "Store Name", custom: true, testValue: "test store" },
      { id: "store_address", label: "Store Address", custom: true, testValue: "4th Park Lane, USA" },
      { id: "store_phone", label: "Store Phone", custom: true, testValue: "+1xxx-xxxxx" },
      { id: "store_email", label: "Store Email", custom: true, testValue: "blueam@gmail.com" },
      { id: "return_reason", label: "Return Reason", testValue: "No return allowed" },
      { id: "customer_name", label: "Customer Name", testValue: "Mr. X customer" },
      { id: "customer_type", label: "Customer Type", testValue: "mental vigilanty" },
      { id: "customer_id", label: "Customer ID", testValue: "#xxxxxx" },
      { id: "loyalty_points_earned", label: "Current Loyalty Points Earned", testValue: "0" },
      { id: "budtender", label: "Employee", testValue: "text budtender" },
      {
        id: "excise_tax_notification",
        label: "Excise Tax Notification",
        custom: true,
        testValue: "*If applicable the cannabis excise taxes are included in the total amount of this invoice.",
      },
      { id: "order_contents", label: "Order Contents", custom: true, type: "custom_html" },
      { id: "order_barcode", label: "Order Barcode", custom: true, type: "barcode", testValue: "test_order_id" },
      { id: "current_datetime", label: "Date & Time", custom: true },
      { id: "ios_app_qr", label: "iOS App QR Code", custom: true, type: "qr" },
      { id: "android_app_qr", label: "Android App QR Code", custom: true, type: "qr" },
    ],
  },
  DELIVERY_RECEIPT: {
    label: "Delivery Receipt",
    fields: [
      { id: "company_logo", label: "Company Logo", custom: true, testValue: "/images/32.png" },
      { id: "print_date", label: "Print Date" },
      { id: "store_id", label: "Store ID", testValue: "#xxxxxx" },
      { id: "order_id", label: "Order ID", testValue: "#xxxxx" },
      { id: "store_name", label: "Store Name", custom: true, testValue: "test store" },
      { id: "store_address", label: "Store Address", custom: true, testValue: "4th Park Lane, USA" },
      { id: "store_phone", label: "Store Phone", custom: true, testValue: "+1xxx-xxxxx" },
      { id: "store_website", label: "Store Website", custom: true, testValue: "https://bleaum.io/" },
      { id: "store_email", label: "Store Email", custom: true, testValue: "blueam@gmail.com" },
      { id: "batch_id", label: "Batch ID", testValue: "#xxxxx" },
      { id: "budtender", label: "Budtender", testValue: "text budtender" },
      { id: "budtenderId", label: "Budtender ID", testValue: "#xxxxx" },
      { id: "return_reason", label: "Return Reason", testValue: "No return allowed" },
      { id: "customer_name", label: "Customer Name", testValue: "Mr. X customer" },
      { id: "customer_type", label: "Customer Type", testValue: "mental vigilanty" },
      { id: "customer_id", label: "Customer ID", testValue: "#xxxxxx" },
      { id: "loyalty_points_earned", label: "Current Loyalty Points Earned", testValue: "0" },
      {
        id: "excise_tax_notification",
        label: "Excise Tax Notification",
        custom: true,
        testValue: "*If applicable the cannabis excise taxes are included in the total amount of this invoice.",
      },
      { id: "order_contents", label: "Order Contents", custom: true, type: "custom_html" },
      { id: "order_barcode", label: "Order Barcode", custom: true, type: "barcode", testValue: "test_order_id" },
      { id: "current_datetime", label: "Date & Time", custom: true },
    ],
  },
  PRE_ORDER_FULFILLMENT_PULL_SHEET: {
    label: "Pre-Order Fulfillment Pull Sheet",
    fields: [
      { id: "store_name", label: "Store Name", testValue: "test store" },
      { id: "order_time", label: "Order Time", custom: true, testValue: "10:39 PM, 1st January, 1900" },
      { id: "order_contents", label: "Order Contents", custom: true },
      { id: "customer_name", label: "Customer Name", testValue: "Mr. X customer" },
      { id: "customer_phone", label: "Customer Phone", testValue: "+1xxx-xxxxx" },
      { id: "delivery_address", label: "Delivery Address", testValue: "4th Park Lane, USA" },
      {
        id: "preorder_notes",
        label: "PreOrder Notes",
        testValue: "Pre orders are only invoked after payment on product arrival",
      },
      { id: "company_logo", label: "Company Logo", custom: true, testValue: "/images/32.png" },
      { id: "order_barcode", label: "Order Barcode", custom: true, type: "barcode", testValue: "#i0uiuritouer" },
      { id: "current_datetime", label: "Date & Time", custom: true },
    ],
  },
};

export const isReceiptType = (type?: string) => type === "RECEIPT" || type === "DELIVERY_RECEIPT";

export const PRESET_DIMENSIONS = [
  { id: "receipt-58mm", name: "58mm Receipt", width: 58, height: 200, unit: "mm" },
  { id: "receipt-80mm", name: "80mm Receipt", width: 80, height: 200, unit: "mm" },
  { id: "receipt-112mm", name: "112mm Receipt", width: 112, height: 200, unit: "mm" },
  { id: "label-2x1", name: "2x1 Label", width: 2, height: 1, unit: "in" },
  { id: "label-3x2", name: "3x2 Label", width: 3, height: 2, unit: "in" },
  { id: "label-4x3", name: "4x3 Label", width: 4, height: 3, unit: "in" },
];
