import {
  LayoutDashboard,
  ShoppingCart,
  Users,
  Tag,
  Boxes,
  LibraryBig,
  Globe,
  Leaf,
  ClipboardList,
  BarChart3,
  Wallet,
  ShieldCheck,
  Truck,
  Settings,
} from "lucide-react";

// Mirrors docs/sidebar-nav-audit.md — currentMenu === "retail".
// guard: { type: "permission" | "parent" | "role" | "any", value }
export const NAV_SECTIONS = [
  {
    key: "admin/dashboard",
    label: "Dashboard",
    icon: LayoutDashboard,
    href: "/admin/dashboard",
    guard: { type: "any" },
  },
  {
    key: "fulfillment",
    label: "Fulfillment",
    icon: ShoppingCart,
    guard: { type: "any" },
    children: [
      { label: "POS", href: "/pos", guard: { type: "permission", value: "SALES_AND_RETURNS.SALES" } },
      { label: "POS (Tablet Mode)", href: "/pos/tablet", guard: { type: "permission", value: "SALES_AND_RETURNS.SALES" } },
      { label: "Order Ahead", href: "/admin/orderahead", guard: { type: "permission", value: "SALES_AND_RETURNS.SALES" } },
      { label: "Front Desk", href: "/admin/front-desk", guard: { type: "any" } },
      { label: "Sales", href: "/admin/orders", guard: { type: "any" } },
      { label: "Returns", href: "/pos/returns", guard: { type: "permission", value: "SALES_AND_RETURNS.SALE_RETURNS" } },
    ],
  },
  {
    key: "customers",
    label: "Customer Mgmt",
    icon: Users,
    guard: { type: "parent", value: "CUSTOMER_MANAGEMENT" },
    children: [
      { label: "Customers", href: "/admin/customer-management/customers", guard: { type: "permission", value: "CUSTOMER_MANAGEMENT.CUSTOMERS" } },
      { label: "Customer Groups", href: "/admin/customers/groups", guard: { type: "permission", value: "CUSTOMER_MANAGEMENT.CUSTOMER_GROUPS" } },
      { label: "Rewards & Types", href: "/admin/customer-management/customer-types-rewards", guard: { type: "permission", value: "CUSTOMER_MANAGEMENT.CUSTOMER_TYPES" } },
    ],
  },
  {
    key: "promotions",
    label: "Promotions",
    icon: Tag,
    guard: { type: "parent", value: "PROMOTIONS" },
    children: [
      { label: "Coupons", href: "/admin/coupons", guard: { type: "permission", value: "PROMOTIONS.COUPONS" } },
      { label: "Deals", href: "/admin/deals", guard: { type: "permission", value: "PROMOTIONS.DEALS" } },
      { label: "Loyalty Reward Settings", href: "/admin/loyalty/reward-settings", guard: { type: "permission", value: "SUPER_ADMIN" } },
    ],
  },
  {
    key: "inventory-management",
    label: "Inventory Mgmt",
    icon: Boxes,
    guard: { type: "any" },
    children: [
      { label: "Inventory & Pricing", href: "/admin/inventory/manage-inventories", guard: { type: "permission", value: "INVENTORY_MANAGEMENT.INVENTORIES" } },
      { label: "Adjustments", href: "/admin/inventory/reconciliation", guard: { type: "permission", value: "INVENTORY_MANAGEMENT.INVENTORIES" } },
      { label: "Inventory Levels", href: "/admin/audit/insights/inventory-on-hand", guard: { type: "any" } },
      { label: "Unit of Measurements", href: "/admin/inventory/uom", guard: { type: "permission", value: "INVENTORY_MANAGEMENT.INVENTORIES" } },
      { label: "Audit", href: "/admin/inventory/audit", guard: { type: "any" } },
      { label: "Transfers", href: "/admin/inventory/transfers", guard: { type: "any" } },
      { label: "Purchase Orders", href: "/admin/inventory/purchase-orders", guard: { type: "any" } },
      { label: "Packages", href: "/admin/inventory/packages", guard: { type: "any" } },
      { label: "Storage Locations", href: "/admin/inventory/storage-locations", guard: { type: "permission", value: "INVENTORY_MANAGEMENT.INVENTORIES" } },
    ],
  },
  {
    key: "catalog",
    label: "Catalog",
    icon: LibraryBig,
    guard: { type: "parent", value: "CATALOG" },
    children: [
      { label: "Products", href: "/admin/catalog/products", guard: { type: "any" } },
      { label: "Classifications", href: "/admin/catalog/classifications", guard: { type: "any" } },
      { label: "Brands", href: "/admin/catalog/manufacturers", guard: { type: "any" } },
      { label: "Product Matrix", href: "/admin/catalog/products/matrix", guard: { type: "any" } },
      { label: "Tags", href: "/admin/settings/tags", guard: { type: "any" } },
      { label: "Strains", href: "/admin/settings/strains", guard: { type: "any" } },
      { label: "Suppliers", href: "/admin/settings/suppliers", guard: { type: "any" } },
    ],
  },
  {
    key: "online-ordering",
    label: "Online Ordering",
    icon: Globe,
    guard: { type: "role", value: "BOTH" },
    children: [
      { label: "Ecom Entities", href: "/admin/ecomm/entities", guard: { type: "any" } },
      { label: "Notifications", href: "/bleaum/notification/my-notification", guard: { type: "any" } },
      { label: "Calendar", href: "/extensions/calendar", guard: { type: "any" } },
      { label: "Loyalty", href: "/bleaum/configurations/loyalty", guard: { type: "any" } },
      { label: "Banners", href: "/bleaum/configurations/banners", guard: { type: "any" } },
      { label: "Chat Config", href: "/bleaum/configurations/chat", guard: { type: "any" } },
      { label: "General", href: "/bleaum/configurations/general", guard: { type: "any" } },
      { label: "Spotlight", href: "/bleaum/configurations/sections", guard: { type: "any" } },
      { label: "Firebase", href: "/bleaum/configurations/firebase", guard: { type: "any" } },
      { label: "Media Links", href: "/bleaum/configurations/media-links", guard: { type: "any" } },
      { label: "Cover Page", href: "/bleaum/configurations/cover-page", guard: { type: "any" } },
    ],
  },
  {
    key: "metrc",
    label: "METRC",
    icon: Leaf,
    guard: { type: "featureScope", value: "METRC_REPORTING" },
    children: [
      { label: "Metrc Reconciliations", href: "/admin/inventory/metrc-reconciliation/packages", guard: { type: "permission", value: "INVENTORY_MANAGEMENT.METRC_RECONCILIATION" } },
      { label: "Metrc Transfers", href: "/admin/inventory/transfers/metrc-transfer", guard: { type: "permission", value: "TRANSFERS.METRC" } },
      { label: "Metrc Configuration", href: "/admin/settings/metrc-configuration", guard: { type: "permission", value: "BOTH" } },
    ],
  },
  {
    key: "audit-log",
    label: "Audit Logs",
    icon: ClipboardList,
    guard: { type: "any" },
    children: [
      { label: "Transactions", href: "/admin/audit/transactions", guard: { type: "permission", value: "CASH_MANAGEMENT.RD" } },
      { label: "ACH Transactions", href: "/admin/audit/ach-transactions", guard: { type: "any" } },
    ],
  },
  {
    key: "reports-analytics",
    label: "Reports & Analytics",
    icon: BarChart3,
    guard: { type: "anyParent", value: ["ANALYTICS", "REPORTING"] },
    children: [
      {
        label: "Analytics",
        guard: { type: "parent", value: "ANALYTICS" },
        children: [
          { label: "Command Center", href: "/admin/sales-report/executive-summary", guard: { type: "permission", value: "ANALYTICS.COMMAND_CENTER" } },
          { label: "Performance Metrics", href: "/admin/sales-report/performance", guard: { type: "permission", value: "ANALYTICS.PERFORMANCE_METRICS" } },
          { label: "Sales Intelligence", href: "/admin/sales-report/sales-intelligence", guard: { type: "permission", value: "ANALYTICS.SALES_INTELLIGENCE" } },
          { label: "Promo Performance", href: "/admin/sales-report/discounts", guard: { type: "permission", value: "ANALYTICS.PROMO_PERFORMANCE" } },
          { label: "Sales Heatmap", href: "/admin/audit/day-and-time", guard: { type: "permission", value: "ANALYTICS.SALES_HEATMAP" } },
          { label: "Supply Tracker", href: "/admin/audit/inventory-reorder", guard: { type: "permission", value: "ANALYTICS.SUPPLY_TRACKER" } },
          { label: "Referral Source", href: "/admin/sales-report/referral-source-report", guard: { type: "permission", value: "ANALYTICS.REFERRAL_SOURCE" } },
        ],
      },
      {
        label: "Reporting",
        guard: { type: "parent", value: "REPORTING" },
        children: [
          { label: "Customer", href: "/admin/sales-report/customer-report", guard: { type: "permission", value: "REPORTING.CUSTOMER" } },
          { label: "Inventory", href: "/admin/sales-report/inventory", guard: { type: "permission", value: "REPORTING.INVENTORY" } },
          { label: "Loyalty", href: "/admin/sales-report/loyalty", guard: { type: "permission", value: "REPORTING.LOYALTY" } },
          { label: "Sales", href: "/admin/sales-report/sales", guard: { type: "permission", value: "REPORTING.SALES" } },
          { label: "Taxes", href: "/admin/sales-report/taxes", guard: { type: "permission", value: "REPORTING.TAXES" } },
        ],
      },
    ],
  },
  {
    key: "cash-management",
    label: "Cash Mgmt",
    icon: Wallet,
    guard: { type: "parent", value: "CASH_MANAGEMENT" },
    children: [
      { label: "Main Vault", href: "/admin/audit/cash-management", guard: { type: "permission", value: "CASH_MANAGEMENT.VAULT" } },
      { label: "Registers", href: "/admin/inventory/registers", guard: { type: "permission", value: "CASH_MANAGEMENT.RD" } },
      { label: "Drawers", href: "/pos/drawers", guard: { type: "permission", value: "CASH_MANAGEMENT.RD" } },
    ],
  },
  {
    key: "access-management",
    label: "Access Mgmt",
    icon: ShieldCheck,
    guard: { type: "any" },
    children: [
      { label: "Team", href: "/admin/access-management/employee", guard: { type: "permission", value: "BOTH" } },
      { label: "Roles", href: "/admin/access-management/role", guard: { type: "permission", value: "BOTH" } },
      { label: "Shifts", href: "/admin/access-management/employee-shift", guard: { type: "any" } },
    ],
  },
  {
    key: "delivery-management",
    label: "Delivery Mgmt",
    icon: Truck,
    guard: { type: "any" },
    children: [
      { label: "Delivery", href: "/admin/delivery-management/delivery-profiles", guard: { type: "any" } },
      { label: "Drivers", href: "/admin/delivery-management/persons", guard: { type: "any" } },
      { label: "Vehicles", href: "/admin/delivery-management/vehicle", guard: { type: "any" } },
      { label: "Delivery Jobs", href: "/admin/delivery-management/jobs", guard: { type: "any" } },
    ],
  },
  {
    key: "settings",
    label: "Settings",
    icon: Settings,
    guard: { type: "any" },
    children: [
      { label: "Shop Preferences", href: "/admin/settings/cashier", guard: { type: "permission", value: "BOTH" } },
      { label: "Integrations", href: "/admin/settings/integrations", guard: { type: "permission", value: "BOTH" } },
      { label: "Tasks", href: "/admin/tasks/tasks-listings", guard: { type: "any" } },
      { label: "Pricing Templates", href: "/admin/settings/pricing-templates", guard: { type: "permission", value: "BOTH" } },
      { label: "Tax", href: "/admin/settings/tax", guard: { type: "permission", value: "INVENTORY_MANAGEMENT.TAXES" } },
      { label: "Hardware Clients", href: "/admin/hardware-clients", guard: { type: "permission", value: "BOTH" } },
      { label: "Print Settings", href: "/admin/print", guard: { type: "permission", value: "BOTH" } },
      { label: "Store Information", href: "/admin/settings/stores-information", guard: { type: "permission", value: "BOTH" } },
      { label: "Reset Password", href: "/admin/change-password", guard: { type: "any" } },
    ],
  },
];
