import { Geist, Geist_Mono } from "next/font/google";
import "./globals.scss";
import { ThemeProvider, noFlashThemeScript } from "@/context/theme-context";
import SettingsPanel from "@/components/settings/SettingsPanel";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        {/* Sets data-theme before paint — prevents flash of default theme on reload. */}
        <script dangerouslySetInnerHTML={{ __html: noFlashThemeScript }} />
      </head>
      <body className="min-h-full flex flex-col">
        <ThemeProvider>
          {children}
          <SettingsPanel />
        </ThemeProvider>
      </body>
    </html>
  );
}
