#!/usr/bin/env node
// One-command environment bootstrap for Tauri dev/build.
//
// Runs before `tauri dev` and `tauri build`. Ensures the two things a fresh
// clone (or new machine) always misses:
//   - Rust toolchain (cargo/rustc), installed via rustup when absent.
//   - The Bun runtime, needed both by `next build`-less dev and the sidecar
//     packaging step. Installed via the official installer when absent.
//
// The sidecar binary and `src-tauri/server/` are gitignored build artifacts.
// Dev mode needs the binary present before `tauri dev` spawns the shell plugin
// sidecar; the server dir is only produced by `next build` (build:sidecar), so
// a plain `bun dev` clone doesn't have it yet — we stub it and let the build
// regenerate it. That keeps `bun run tauri:dev` working on a cold checkout.
import { execSync, spawnSync } from "node:child_process";
import { existsSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { platform, arch } from "node:os";

const root = process.cwd();
const binariesDir = join(root, "src-tauri", "binaries");
const serverDir = join(root, "src-tauri", "server");

const ok = (msg) => console.log(`  \x1b[32m✓\x1b[0m ${msg}`);
const info = (msg) => console.log(`  \x1b[36m→\x1b[0m ${msg}`);
const warn = (msg) => console.warn(`  \x1b[33m!\x1b[0m ${msg}`);

const which = (bin) => {
  try {
    return execSync(process.platform === "win32" ? `where ${bin}` : `which ${bin}`, {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    })
      .trim()
      .split("\n")[0];
  } catch {
    return "";
  }
};

const has = (bin) => which(bin) !== "";

// Sidecar naming: `<name>-<target-triple>`, same as scripts/build-sidecar.mjs.
const rustHost = () =>
  execSync("rustc -vV", { encoding: "utf8" })
    .match(/^host: (.+)$/m)?.[1]
    .trim();

const expectedSidecar = () => {
  const triple = process.env.SIDECAR_TARGET ?? rustHost();
  if (!triple) return "";
  const os = platform();
  const archMap = {
    x64: "x86_64",
    arm64: "aarch64",
  };
  return join(binariesDir, `bun-${triple}${os === "win32" ? ".exe" : ""}`);
};

console.log("\n\x1b[1mTauri environment check\x1b[0m");

// --- Rust toolchain -------------------------------------------------------
if (has("cargo") && has("rustc")) {
  ok(`Rust toolchain (${rustHost()})`);
} else {
  warn("Rust not found — installing via rustup.");
  info("This downloads and installs Rust; may take a few minutes.");
  if (platform() === "win32") {
    // rustup-init.exe is the official Windows route.
    console.log("  Downloading rustup-init.exe...");
    execSync(
      'powershell -Command "Invoke-WebRequest https://win.rustup.rs/x86_64 -OutFile $env:TEMP\\rustup-init.exe"',
      { stdio: "inherit" }
    );
    execSync(`"${process.env.TEMP}\\rustup-init.exe" -y --profile minimal`, { stdio: "inherit" });
  } else {
    console.log("  Downloading rustup-init.sh...");
    execSync('curl --proto "=https" --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal', {
      stdio: "inherit",
    });
  }
  if (!has("cargo") && !has("rustc")) {
    warn("Rust installed but not on PATH. Restart your shell, or run `source ~/.cargo/env` first.");
  } else {
    ok("Rust toolchain");
  }
}

// --- Bun runtime ----------------------------------------------------------
if (has("bun")) {
  ok(`Bun (${which("bun")})`);
} else {
  warn("Bun not found — installing via the official installer.");
  info("The build scripts use `bun run` and the sidecar bundles the bun binary.");
  const installer =
    platform() === "win32" ? "powershell -c \"irm bun.sh/install.ps1 | iex\"" : "curl -fsSL https://bun.sh/install | bash";
  execSync(installer, { stdio: "inherit" });
  if (!has("bun")) {
    warn("Bun installed but not on PATH. Restart your shell, or run `source ~/.bun/bin` first.");
  } else {
    ok("Bun");
  }
}

// --- Sidecar / server dirs (dev-mode prerequisites) -----------------------
const sidecar = expectedSidecar();
if (sidecar && existsSync(sidecar)) {
  ok(`Sidecar bun binary (${sidecar.replace(root, ".")})`);
} else {
  warn(
    sidecar
      ? `Missing sidecar binary: ${sidecar.replace(root, ".")}`
      : "Cannot resolve the sidecar binary (is rustc on PATH?)"
  );
  info("Run `bun run build:sidecar` once to generate it, or just run `bun run tauri:build`.");
}

// The server dir is regenerated by every `next build` (build:sidecar); a stub
// keeps `tauri dev` from breaking when only `next dev` has ever run.
if (existsSync(join(serverDir, "server.js"))) {
  ok(`Server bundle (${serverDir.replace(root, ".")})`);
} else {
  warn(`Missing server bundle (${serverDir.replace(root, ".")}) — stubbing; build:sidecar will regenerate it.`);
  mkdirSync(serverDir, { recursive: true });
}

console.log("");
